# Generated by Django 4.2.7 on 2023-12-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="brd_image/%Y-%m-%d/"
            ),
        ),
    ]
