# Generated by Django 4.2.7 on 2023-12-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brd", "0004_alter_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.CharField(max_length=300),
        ),
    ]
