# Generated by Django 5.0 on 2024-01-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CameraImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="camera/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
