# Generated by Django 4.2.7 on 2024-01-04 05:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_posturedetection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posturedetection",
            name="user",
        ),
    ]
