# Generated by Django 5.0 on 2024-01-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cameraimage",
            name="image",
            field=models.ImageField(upload_to="camera/"),
        ),
    ]
