# Generated by Django 4.2.7 on 2024-01-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brd", "0006_delete_user_alter_comment_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(max_length=200),
        ),
    ]
